version: 1.0.{build}
branches:
  only:
  - master
  - development
  - ^version-.*$
image: Visual Studio 2019
configuration: Release
clone_depth: 1
before_build:
- cmd: dotnet restore
build:
  project: Jewellery2.0/GoldJewelry.sln
  verbosity: minimal
